removed dropdown for 'Add Dataset'
oss-slu/MeltShiny pull request #186
Opened 2024-09-16 00:24 UTC by avazzano7

Fixes #176 

What was changed?

The dropdown menu from the Files tab has been removed, so when you click on 'Files', it will bring you to the page where you input a file into the system.

Why was it changed?

This was changed because the dropdown menu was redundant and the File tab can have the same functionality on its own.

How was it changed?

ui.R was updated so that the Files tab no longer is a dropdown menu, but is now a tabPanel button on its own.

How was it tested

Program was run and the 'Add Dataset' dropdown menu has been removed, with the File button having all of its functionality.

Screenshots that show the changes (if applicable):

2024-09-16 22:13 UTC, Canada101 reviewed
great work got rid of the dropdown functionality but retained the existing functionality of the file button. got rid of the tabPanel title = add data set and kept the code that was for the file button.

2024-09-16 22:15 UTC, Canada101 requested changes
got rid of the second tab panel that added the dropdown for add dataset and kept the existing code for the button. Change was simple and easily implemented great job.

2024-09-18 21:33 UTC, BollepalliPranitha approved these changes
The removal of the "Add Dataset" dropdown menu simplifies the user interface. By consolidating dataset selection and configuration into the "File" tab, the UI becomes more intuitive and less cluttered.
The functionality of the "File" tab has been preserved, with all necessary inputs and options retained.
The code is clean and consistent with the original style.
The changes are straightforward and can be easily understood.
@avazzano7 Great Job

2024-09-21 17:30 UTC, avazzano7 reviewed
Thanks for the review, Sam

2024-09-22 18:36 UTC, Canada101 approved these changes

2024-09-22 18:39 UTC, merged