Remove unnecessary words in the help tab #173
oss-slu/MeltShiny pull request #187
Opened 2024-09-16 01:13 UTC by srepalli3

Fixes #173

**What was changed?**

The unnecessary words " # nolint" has been removed from the general information tab. 

**Why was it changed?**

Deleting the words allows for better readability, it was necessary to delete the word since it has no place in the general information tab. 

**How was it changed?**

ui.R was updated so that the "#nolint" comment was removed from the actual text. 

**How was it tested**

Looked through the ui.R script to ensure that the comments were gone from the actual text.

2024-09-16 22:13 UTC, avazzano7 commented on code/.Rhistory
> +length_t_test <- t.test(parrots_data$Length_Live, parrots_data$Length_Playback, na.action = na.omit)
This .Rhistory file may not need to be merged into the main branch

2024-09-16 22:16 UTC, avazzano7 requested changes

2024-09-16 22:16 UTC, avazzano7 commented on code/.Rhistory
> +length_t_test <- t.test(parrots_data$Length_Live, parrots_data$Length_Playback, na.action = na.omit)
this .Rhistory file may not need to be merged

2024-09-18 01:41 UTC, kate-holdener commented on code/.Rhistory
> +length_t_test <- t.test(parrots_data$Length_Live, parrots_data$Length_Playback, na.action = na.omit)
looks like maybe this file should be added to .gitignore

2024-09-18 21:36 UTC, BollepalliPranitha commented on code/.Rhistory
> +length_t_test <- t.test(parrots_data$Length_Live, parrots_data$Length_Playback, na.action = na.omit)
Yes , I will be adding the .Rhistory file to .gitignore

2024-09-18 21:37 UTC, BollepalliPranitha requested changes
The unnecessary word #nolint is removed from the Help page 
But when I tried uploading the data and after clicking on upload data 
I got this error

![image](https://github.com/user-attachments/assets/d7b90418-8f77-441f-9b0d-5d14d1c54a59)

These are the input details
AYGU-1_MeltR.csv
Sample 1
No Blanks
Wavelength – 260
Nucleic acid type – RNA
Sequence – GACUAGUU
Molecular state - Homoduplex

2024-09-19 19:45 UTC, srepalli3 commented
> Merging can be performed automatically once the requested changes are addressed.

I fixed this by rebasing my branch with main.

2024-09-21 20:29 UTC, BollepalliPranitha approved these changes
Great work on cleaning up the code by removing the unnecessary # nolint comments! This change improves code quality and aligns with best practices by keeping the codebase clean and free from unnecessary tags.
The removal of the # nolint comments is appropriate, as it does not affect core logic.
There are no performance concerns associated with this change.

2024-09-21 20:45 UTC, avazzano7 approved these changes

2024-09-22 15:34 UTC, kate-holdener commented on code/.Rhistory
> +length_t_test <- t.test(parrots_data$Length_Live, parrots_data$Length_Playback, na.action = na.omit)
@srepalli3 please remove .Rhistory file from this pull request. To do this, from your clone of the repo from the fix/issue_173 branch run:
git rm .Rhistory
git commit -m 'removed Rhistory'
git push

2024-09-22 15:34 UTC, kate-holdener requested changes
Please remove .Rhistory file from this PR.

2024-09-22 19:19 UTC, srepalli3 commented on code/.Rhistory
> +length_t_test <- t.test(parrots_data$Length_Live, parrots_data$Length_Playback, na.action = na.omit)
will do, thank you!

2024-09-22 22:38 UTC, merged

2024-09-22 22:43 UTC, BollepalliPranitha commented
@srepalli3 The code has been thoroughly tested, and all functionalities are working as expected.

There were some merge conflicts with the fix/issue_173 branch. I have resolved the conflicts and successfully merged your code into that branch.