changed the formatting of the html text for the help page by removing…
oss-slu/MeltShiny pull request #188
Opened 2024-09-16 19:32 UTC by Canada101

… the bullet points and adding separation between paragraphs and pragraph headers. Additionaly changed the punctuation for headers to be all uppercase

Fixes #issue_number_171

**What was changed?**
I changed the formatting of the text on the page by removing the bullet point syntax and additionally got rid of the unnecessary no lint text as well. More lines were added to increase readability separating section headers and individual paragraphs.   
*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
I changed the help page, specifically removal of <li> and #no lint as they were not needed and then added additional borders to make distinctions between headers and blocks of text. The headers for different sections were fully capitalized as well.
**Why was it changed?**
This was changed to make the page more readable and to make it look more organized and professional.
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
there was not really an issue with the code it was simply changing the way the text was formatted so I replaced the previous formatting.
**How was it changed?**
Deleting the old formatting
*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*
I modified the ui file and the most important lines were the one containing no lint and <li> at the beginning of the text as that was the formatting to make bullet points
**How was it tested**
repeatedly running the code to ensure the text was displayed properly as their is no user interaction aside from navigating to the page
*Here, get into detail about how you tested the files you modified.
Adjusting the size of the window and taking different navigation routes to the help page.
**Screenshots that show the changes (if applicable):**

2024-09-16 22:07 UTC, srepalli3 commented on code/ui.R
> +        hr(style = "border-top: 1px solid #000000;"),
Do you think it is possible to put the text in one HTML parentheses? Or do you have to have each section separately?

2024-09-16 22:07 UTC, srepalli3 commented on code/ui.R
>        )
Same thing throughout the rest of your edits, I think you should test to see whether or not it is possible to have each section in one "HTML(...)" instead of having separate ones.

2024-09-16 22:14 UTC, srepalli3 requested changes

2024-09-16 22:14 UTC, srepalli3 commented on code/ui.R
> +
Same thing throughout the rest of your edits, I think you should test to see whether or not it is possible to have each section in one "HTML(...)" instead of having separate ones.

2024-09-16 22:14 UTC, srepalli3 commented on code/ui.R
> +        hr(style = "border-top: 1px solid #000000;"),
Do you think it is possible to put the text in one HTML parentheses? Or do you have to have each section separately?

2024-09-18 21:38 UTC, BollepalliPranitha requested changes
Suggestion 1:
Current Implementation: Some HTML content includes closing </li> tags without corresponding opening <li> tags.
Suggestion: To adhere to proper HTML standards, ensure that each closing </li> tag is paired with an opening <li> tag. Properly formatted HTML improves readability and avoids potential issues with rendering. Here to remove the bullet points <li> is removed from the code
Please ensure to remove </li> as well.
Suggestion 2:
Current Implementation: The HTML() function is used multiple times to add content, with each section separated into individual HTML() calls.
Suggestion: For better organization and maintainability, consider combining the entire HTML content into a single HTML() block. This approach reduces redundancy and makes the code cleaner.

2024-09-22 22:32 UTC, BollepalliPranitha approved these changes

2024-09-22 22:38 UTC, BollepalliPranitha approved these changes
The recent changes in the PR have addressed the suggestions provided, and everything is working as expected. 
Original Issue: Some HTML content contained closing tags without corresponding opening tags, which violated HTML standards.
Implementation: The developer has corrected this by ensuring that every closing tag has a corresponding opening tag. This aligns with proper HTML standards, improving the readability and preventing potential rendering issues and no further issues with unmatched tags are present. 
Original Issue: Multiple separate HTML() calls were used to add content, leading to redundancy and disorganization.
Implementation: The HTML content has been successfully combined into a single HTML() block, improving organization and reducing the redundancy in the code.
The new approach of using a single HTML() block makes the code more concise and easier to maintain. The changes were implemented effectively, and the functionality remains intact.
Great work

2024-09-22 22:38 UTC, merged

2024-09-22 22:42 UTC, BollepalliPranitha commented
@srepalli3 The code has been thoroughly tested, and all functionalities are working as expected.

There were some merge conflicts with the fix/issue_173 branch. I have resolved the conflicts and successfully merged your code into that branch.