Add Back Button and Hide Input Section After Dataset Upload #196
oss-slu/MeltShiny pull request #200
Opened 2024-10-14 03:43 UTC by Canada101

Fixes #issue_196

**What was changed?**

I added the hiding of the input side bar upon entering a dataset and a back button that would appear after inputting data and make the sidebar reappear. 

**Why was it changed?**

This was changed to make the ui flow better and give a more professional look and user experience.

**How was it changed?**

I added a label to the sidebar and a separate back action button that was not visible upon starting the program. this was done in the ui file. When the upload data button is clicked the sidebar gets hidden and the back button appears and when the back button is clicked this brings up the side bar. this was done by adding logic in the server file for when the buttons are clicked.

**How was it tested**

I tested this by running test files and ensuring you could see the back button and that when clicking it would bring back the sidebar. 
[backButtonCapstoneIssue.pdf](https://github.com/user-attachments/files/17359078/backButtonCapstoneIssue.pdf)

**Screenshots that show the changes (if applicable):**

2024-10-14 22:27 UTC, srepalli3 approved these changes

2024-10-14 22:27 UTC, srepalli3 commented on code/ui.R
> +          )
good job! very clear and concise

2024-10-14 22:27 UTC, srepalli3 commented on code/server.r
> +  })
again, clear and concise

2024-10-15 18:24 UTC, kate-holdener commented
I think the "Back" button is confusing and doesn't resolve the issue of the application not being responsive (you can't upload another dataset). Also, once you use the "Back" button, there is no way to hide the left hand menu again. The "Back" button would make sense if it allowed us to get back to the menu and change parameters, but it doesn't allow us to change parameters. 

Once the left hand menu disappears, the output looks strangely offset to the right, with a lot of blank space on the left.
<img width="1485" alt="Screenshot 2024-10-15 at 1 15 41 PM" src="https://github.com/user-attachments/assets/133fd28d-b928-40be-b0e3-d538e41f8965">


Having the file upload menu disappear makes sense after the upload, I'm not sure if "Back" really makes sense. I've played with the application, and it feels awkward. Also, when switching the dropdown menu to show many entries (100), the back button ends up at the bottom and is hard to find.

@BollepalliPranitha @Canada101 I encourage you to carefully think through the design here to improve usability of the application.

2024-10-15 21:05 UTC, Massi-Papi commented
> I think the "Back" button is confusing and doesn't resolve the issue of the application not being responsive (you can't upload another dataset). Also, once you use the "Back" button, there is no way to hide the left hand menu again. The "Back" button would make sense if it allowed us to get back to the menu and change parameters, but it doesn't allow us to change parameters.
> 
> Once the left hand menu disappears, the output looks strangely offset to the right, with a lot of blank space on the left. <img alt="Screenshot 2024-10-15 at 1 15 41 PM" width="1485" src="https://private-user-images.githubusercontent.com/42073871/376740661-133fd28d-b928-40be-b0e3-d538e41f8965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjUxMDIsIm5iZiI6MTcyOTAyNDgwMiwicGF0aCI6Ii80MjA3Mzg3MS8zNzY3NDA2NjEtMTMzZmQyOGQtYjkyOC00MGJlLWIwZTMtZDUzOGU0MWY4OTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDIwNDAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNWM5YmIyY2MyM2JiNTJiNzY4YWUyNDZiMTlhMTU4Y2ZmNWI5NzZjYzU5NzhiNjFiMzFkYWNiY2Q5Mzg1YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mxNbgyQlfkzKfUVB0Wi9z70LtXxBVxwxGjb3jyzj4po">
> 
> Having the file upload menu disappear makes sense after the upload, I'm not sure if "Back" really makes sense. I've played with the application, and it feels awkward. Also, when switching the dropdown menu to show many entries (100), the back button ends up at the bottom and is hard to find.
> 
> @BollepalliPranitha @Canada101 I encourage you to carefully think through the design here to improve usability of the application.

I agree with this. Once you hit the "back" button, you can't really do anything. It just brings you back to the main page, and you aren't able to input anything new. 
It also appears whenever you hit "Upload Data", and it is a bit of a nuisance on the screen. You should have the button hidden until everything loads. A good way to do that is with a boolean: `False = Hidden, True = Showing`
Especially with the reset data button that will incorporated later, this isn't necessary.

2024-10-17 06:05 UTC, BollepalliPranitha commented
The primary goal of introducing the "Back" button was to enhance user experience by temporarily hiding the unresponsive input section after a dataset upload, allowing the user to focus on the full display of the data table. The idea was to provide a clear view of the uploaded data without distractions while ensuring users have an accessible way to return to the input form for resetting or updating the dataset if needed.
@Canada101 
However, as noted, the current implementation does not fully address the issue regarding layout and responsiveness. The blank space on the left after the input section is hidden creates an imbalance in the interface, making the output look offset to the right.
The "Back" button currently appears whenever "Upload Data" is clicked, which is visible while the data is still loading. We should only show the "Back" button after the dataset has fully loaded to avoid unnecessary clutter. 
We need to discuss and plan a more effective approach to incorporate these changes while ensuring a seamless user experience.

2024-11-05 22:44 UTC, BollepalliPranitha requested changes
The current implementation does not fully address the issue regarding layout and responsiveness. The blank space on the left after the input section is hidden creates an imbalance in the interface, making the output look offset to the right.

2024-12-07 04:04 UTC, BollepalliPranitha commented
As this is not working as expected , and being a low priority issue, closing this PR

2024-12-07 04:04 UTC, closed without merging