temperatureID autopopulates with the highest temp in the dataset
oss-slu/MeltShiny pull request #201
Opened 2024-10-14 15:31 UTC by avazzano7

Fixes #190 

**What was changed?**

The textInput that prompts the user to input a temperature now autopopulates with the highest temperature found in the dataset.

**Why was it changed?**

This change was made to aid the user so they won't have to do as many steps to process the data.

**How was it changed?**

The dataset is opened and the highest temperature in the "Temperature" column is extracted. This temperature is inputted into the inputText field so that the user can see which temperature is being used.

**How was it tested**

The program was run with test files and the correct max temperature was found and used.

2024-10-14 22:29 UTC, Canada101 requested changes
Make it so that the user is not able to enter a number for temperature before uploading the data.

2024-10-14 22:29 UTC, Canada101 commented on code/ui.R
> -            label = "Enter the temperature used to calculate the concentration with Beers law", # nolint
Update this such that it is either an input that is disabled then re enabled to prevent user input or make it a different button or format.

2024-10-15 03:29 UTC, kate-holdener commented
@avazzano7 can you provide details of the test files you used and the exact steps taken to test?

2024-10-15 15:32 UTC, avazzano7 commented
> @avazzano7 can you provide details of the test files you used and the exact steps taken to test?

Yes, the main test file we've been using is 
[AYGU-1_MeltR.csv](https://github.com/user-attachments/files/16919324/AYGU-1_MeltR.csv)
(this file is also located in the root directory)

Below are the parameters needed to test this dataset:

AYGU-1_MeltR.csv
No Blanks
Wavelength – 260
Nucleic acid type – RNA
Sequence – GACUAGUU
Molecular state - Homoduplex

2024-10-15 15:33 UTC, avazzano7 commented on code/ui.R
> -            label = "Enter the temperature used to calculate the concentration with Beers law", # nolint
Just made a new commit where it disables the temperatureID button at the start of the program so it still displays, but the user isn't allowed to make manual inputs

2024-10-15 18:33 UTC, kate-holdener commented
I get an error when run the code from this branch:
[2024-10-15 13:31:11] | INFO | ANALYSIS PLOTS RENDERED  
Warning: Error in character: invalid 'length' argument
  114: character
  113: shinyInput [/Users/holdener/repos/MeltShiny/code/server.R#531]
  112: <reactive:getListUnder> [/Users/holdener/repos/MeltShiny/code/server.R#541]
   96: getListUnder
   83: observe [/Users/holdener/repos/MeltShiny/code/server.R#558]
   82: <observer:observeEvent(datasetsUploadedID())>
   81: valueFunc
   68: func
   66: f
   65: Reduce
   56: do
   55: hybrid_chain
   54: observeEvent(datasetsUploadedID())
   53: contextFunc
   52: env$runWith
   45: ctx$run
   44: run
   25: flushCallback
   24: FUN
   23: lapply
   22: ctx$executeFlushCallbacks
   21: .getReactiveEnvironment()$flush
   20: flushReact
   19: serviceApp
   12: runApp
   10: eval
    9: eval
    8: sourceUTF8
    7: func
    6: appObj
    5: shinyAppDir_appR
    4: shinyAppFile
    3: as.shiny.appobj.character
    1: shiny::runApp

2024-10-15 18:34 UTC, kate-holdener commented on code/ui.R
> +            value = "",
If the value is auto-populated, this textInput is unnecessary.

2024-10-15 20:48 UTC, Massi-Papi commented
Looks good, and your code is great.

2024-10-15 20:48 UTC, Massi-Papi approved these changes

2024-10-17 05:45 UTC, BollepalliPranitha commented
The code changes look good, and you've done a great job on this implementation. However, based on the updated client requirements, an enhancement to the temperature field is needed.

I have created a new issue (#208) outlining the necessary adjustments. Please review the new issue and implement the required changes to align with the latest specifications.

Once the additional enhancement is completed, I will proceed with merging the code as a whole.

2024-10-24 20:03 UTC, merged