error checking for missing or incorrectly checking the blank checkbox…
oss-slu/MeltShiny pull request #212
Opened 2024-10-28 20:15 UTC by Canada101

… works and a message is displayed to the user identifying the issue. This brings about another issue that needs solving and that is once the program hits any of the defined error checking and fails it does not automatically reset

Fixes #issue_number

**What was changed?**
I added error checking for the no blanks checkbox either being clicked incorrectly or missed and having blanks
*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
I changed the server logic to include checking the input file for blanks
**Why was it changed?**
This code was added to account for user error when interacting with the program
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
This code corrects the user error when incorrectly filling out the input fields and notifies them of what they need to change
**How was it changed?**
How it was specifically changed is there was no error checking on the button before and that lead to crashed with no description. This change allows the user to identify the error in input and as of now refresh the program and have the input be correct
*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*
I modified the server file and the most important line is  "has_blanks <- any(is.na(dataset)) || any(dataset == "NA") " which scans the file for blanks the that value is checked against the checkbox allowing for error identification 

**How was it tested**
I tested this by running the same file in the described issue and getting the notification to pop up correctly when running the program 
*Here, get into detail about how you tested the files you modified.
I tested them by doing clicking and not clicking the checkbox for different files after seeing their correct inputs to determine the error was being caught successfully 
**SIDE NOTE**
One of the pull requests currently up from last week that is not merged is the reset button with reset functionality. If that code is merged I can incorporate the logic into the next sprint and have errors that are caught reset the fields so the user does not need to restart the program. 
**Screenshots that show the changes (if applicable):**

2024-10-28 22:44 UTC, avazzano7 commented
After reset button is created (this is in its own PR), this can be worked on further - fields need to be passed properly to avoid R crashing due to improper parameters

2024-10-28 22:48 UTC, avazzano7 requested changes
After reset button is created (this is in its own PR), this can be worked on further - fields need to be passed properly to avoid R crashing due to improper parameters

2024-10-29 22:25 UTC, BollepalliPranitha requested changes

2024-10-29 22:25 UTC, BollepalliPranitha commented on code/server.r
Even with the error notification, if users delay clicking "Understood" or even if they do click it, the app still crashes. This suggests that while the error notification logic is functional, additional changes may be necessary to stabilize the application during error states.
![image](https://github.com/user-attachments/assets/04d7fccf-76b6-40c4-b2a3-7dd6b8bfc03f)
**Special Note:**
Extending the validation to scan for missing sequences before further processing can help avoid crashes and provide a clear message to users about missing required data.

2024-10-29 22:26 UTC, BollepalliPranitha commented on code/server.r
Try to mention Fixes #issue_number while creating the PR

2024-12-07 03:53 UTC, BollepalliPranitha commented
This issue is being handled by another PR
https://github.com/oss-slu/MeltShiny/pull/221
So closing this issue

2024-12-07 03:53 UTC, closed without merging