Remove Unnecessary Delete and ID Columns from IndividualFits *.xlsx Ouput #214
oss-slu/MeltShiny pull request #219
Opened 2024-11-06 00:20 UTC by srepalli3

Fixes #214

**What was changed?**
I deleted unnecessary columns from IndividualFits *.xlsx output that is downloaded

**Why was it changed?**
These columns are not necessary, and presented an obstruction to the file's readability and relevance.

**How was it changed?**
I changed the server.r file, specifically lines 663-685. Implemented condiitional removal by adding "select(-c(Delete, ID))" specifically for individual fits. In addition, when "All of the Above" is selected, my additions ensure that the two columns are still not included in IndividualFits. 

**How was it tested**
I reran the MeltShiny command two times, inputted all test data, downloaded the excel file with first "Individual Fits" selected and then with "All of the Above" selected to ensure that the two columns were not present. 

**Screenshots that show the changes (if applicable):**
Before:
<img width="533" alt="before deleted delete:id columns" src="https://github.com/user-attachments/assets/b644c6ab-85aa-48bb-b6e5-feb480f77495">
After:
<img width="457" alt="removed delete:id columns" src="https://github.com/user-attachments/assets/9ad2a6ea-69e1-4557-a2a7-32be4e4be84f">

2024-11-11 23:17 UTC, avazzano7 approved these changes
Changes to the extra columns are good and functional

2024-11-13 04:28 UTC, BollepalliPranitha requested changes
@srepalli3 The changes mentioned are working fine 
But when I tried to download the results in csv format, I was unable to do that.
Before changes
![image](https://github.com/user-attachments/assets/b03b45af-c19b-4337-803b-0571092b213d)
I was able to download it in csv format
After changes
 I was unable to download it in csv format
 ![image](https://github.com/user-attachments/assets/d04deb33-1a90-4d22-a809-6f58403bf8a2)
Please look into that and make the required changes.

2024-11-13 04:46 UTC, srepalli3 commented
issue should be fixed now

2024-11-15 03:14 UTC, BollepalliPranitha approved these changes
@srepalli3 Great work 
It works as expected

2024-11-18 08:32 UTC, merged