Issue216
oss-slu/MeltShiny pull request #220
Opened 2024-11-11 15:58 UTC by avazzano7

Fixes #216

**What was changed?**
Individual Fits data on the results tab is now displayed. It is automatically changed when points are removed from the Van't Hoff plot.

**Why was it changed?**
The Individual Fits data was not being displayed before.

**How was it changed?**
vals$keeprows is a reactive value which is used to track the points that are left on the Van't Hoff plot. A reactive function called filteredFitData is based on vals$keeprows and ensures that only the data for the current points is displayed on the Individual Fits table of the results tab.

**How was it tested**
Points were removed from the Van't Hoff plot and it was made sure that the same points' data were removed from the Individual Fit table automatically.

2024-11-11 23:23 UTC, Canada101 requested changes
write code that adapts the "summary of the three methods" data box to the deletion of data points

2024-11-13 04:37 UTC, BollepalliPranitha reviewed
@avazzano7 
![image](https://github.com/user-attachments/assets/ede16904-61ae-4757-981a-660fc6d7541d)
what is the purpose of this remove button

2024-11-15 04:30 UTC, BollepalliPranitha reviewed
As Discussed , created 2 sub tasks for this issue 
The removed points are visible in the results section.
But still need to enable the summary table to recalculate thermodynamic parameters based on the modified plot data.
Marking the first subtask as completed.

2024-12-07 04:03 UTC, BollepalliPranitha requested changes
@avazzano7 
I was able to see the updated changes in Vant Hoff Plot is being displayed in table you created.
Now I was unable to download all parts of the data
When I download the data, only Individual Fits and Percent Error is being downloaded
But I cant see any Method summaries being downloaded
Also I cant see the reflected changes in the table being downloaded as a part of Individual Fits
![image](https://github.com/user-attachments/assets/334228da-4a2b-456b-b047-0d768950943c)
![image](https://github.com/user-attachments/assets/68b7ea15-6935-4ac7-9c06-d2442bbacf6c)

2024-12-08 17:50 UTC, avazzano7 commented
I just made a new commit that fixed the downloading problem.

2024-12-09 01:57 UTC, BollepalliPranitha commented
Great, But this change needs client review and acceptance before being merged

2025-02-22 07:14 UTC, closed without merging