Issue_404
oss-slu/MeltShiny pull request #221
Opened 2024-11-11 19:46 UTC by Canada101

Fixes #217 

**What was changed?**
I changed the functionality of the input checking for the program so that if input parameters are not met as specified then code that could potentially crash the server does not run as well as included my input error detection that was from sprint 4. This issue combines the changes I needed to make for sprint 4 as well as introducing new logic for input error detection. 
*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
I changed the server file by adding req(is_valid_input) to blocks of code that ran at the same time as the input checking was done and return() where the input checking was done.
**Why and How was it changed?**
This was changed because although input errors were caught nothing was preventing the rest of the server from running the events gated by datasetUploadedID and the press of the upload data button causing the server to crash entirely and need to be restarted
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
The issue with the code previously is that even if errors were caught the code in that block would continue to execute and set is_valid_input to true regardless of if the input error would cause the building of the melt.r object to crash the server. There was no logic at all behind the input error checking so all it did was display what the issue was and crash the server. My code fixes this error and establishes a new protocol for input error handling. By settting is_valid_input to false to start and having the code blocks execute sequentially, the code must pass the error tests to set the is_valid_input to true. This is where return() function comes in as it stops the execution of the code block that sets the valid input to true and does not display valid input preventing the blocks of code that use req(is_valid_input) from running and crashing the server. The req(is_valid_input) ensures that blocks of code dependent on correct user input do not run unless is_valid_input is set to true preventing runtime errors and server crashes. 

*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*
I modified only the server file as this is where all the logic was stored that was causing the runtime errors. The hardest part about fixing the issue was deducing a system to prevent code from running as there are multiple blocks that execute independently from each other using the same observe event or datasetsUploadedID criteria. By ensuring the input error checking actually stopped the is_valid_input from being set to true using return() and requiring it be true to run the other blocks of code using req(is_valid_input) I created a protocol that can be expanded upon and maintained should any other further input issues be discovered
**How was it tested**
I tested this using the error found in issue212 ensuring the error was caught and the server did not crash then reset the program using the reset button and tested the correct inputs to ensure that the program could encounter an error be reset and be re ran correctly without closing the program and re opening it. 
*Here, get into detail about how you tested the files you modified.
I did use some loginfo commands to verify that error checking was being caught and that places where the code would crash would be marked as every block printed out if it ran successfully in order so that when the program crashed i could identify which specific blocks needed the valid input requirements. 
**Screenshots that show the changes (if applicable):**

2024-11-11 23:22 UTC, srepalli3 requested changes
good job!! this pr will fix the issue of our entire program crashing when an error is encountered.

2024-11-11 23:22 UTC, srepalli3 commented on code/server.r
> +      has_blanks <- any(is.na(dataset)) || any(dataset == "NA")
could we not just do this to get rid of redundancy? : has_blanks <- any(is.na(dataset) | dataset == "NA"). This approach would use a single check instead of calling any() twice

2024-11-13 04:54 UTC, BollepalliPranitha requested changes
@Canada101 
If No Blanks was not checked, then the application is showing an alert. When I click on Understood, I was unable to choose No Blanks again. 
![image](https://github.com/user-attachments/assets/67621fc8-a231-4af3-8d8d-53552a5f2970)
I need to click on Reset Data again
This change is not handling Specify sequences
When I don't specify any Sequence The application still crashes
Even if I don't add any dataset and click on upload the application crashes again.

2024-12-07 03:41 UTC, BollepalliPranitha requested changes
@Canada101 
Empty Sequence is handled .
But
If No Blanks was not checked, then the application is showing an alert. When I click on Understood, I was unable to choose No Blanks again.
![image](https://github.com/user-attachments/assets/15ee74ba-e53f-4b32-a8eb-fe423075461d)
I need to click on Reset Data again
Every time clicking again on reset button after wrong input might not be the perfect way to handle this 
Is there any possible way that we can allow the user to to provide the inputs after cliking on understood button?

2024-12-11 05:54 UTC, BollepalliPranitha approved these changes
Great Work
Working as expected

2024-12-14 21:04 UTC, merged